autofetch_sources: true
networks:
  default: mainnet-fork
  mainnet-fork-alchemy:
    explorer: https://api.etherscan.io/api
    cmd: ganache-cli
    cmd_settings:
      accounts: 50
      mnemonic: brownie
      fork: https://eth-mainnet.alchemyapi.io/v2/$ALCHEMY_API_KEY
      default_balance: 500 ether
      chain_id: 1
reports:
  exclude_paths:
    - contracts/mocks/**/*.*
