name: pre-commit

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.0
